import { forwardRef } from 'react'
import type { ScrollSnapSectionProps } from './scrollSnap.types'
import { buildScrollSnapSectionProps } from './scrollSnap.utils'

/**
 * Plain section element that participates in the page snap system.
 *
 * Most of the snap behavior is generated by buildScrollSnapSectionProps so this
 * component stays aligned with BackgroundSection, which uses the same helper.
 */
export const ScrollSnapSection = forwardRef<
  HTMLElement,
  ScrollSnapSectionProps
>(function ScrollSnapSectionRoot(
  {
    className,
    fullHeight,
    snapAlign,
    snapOffset,
    snapStop,
    settledThreshold,
    style,
    ...props
  },
  forwardedRef,
) {
  const snapProps = buildScrollSnapSectionProps({
    className,
    fullHeight,
    snapAlign,
    snapOffset,
    snapStop,
    settledThreshold,
    style,
  })

  return <section ref={forwardedRef} {...snapProps} {...props} />
})
