/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as localeChar123LocaleChar125RouteRouteImport } from './routes/($locale)/{-$locale}/route'
import { Route as localeChar123LocaleChar125IndexRouteImport } from './routes/($locale)/{-$locale}/index'
import { Route as localeChar123LocaleChar125ContactRouteImport } from './routes/($locale)/{-$locale}/contact'
import { Route as localeChar123LocaleChar125BlogIndexRouteImport } from './routes/($locale)/{-$locale}/blog/index'
import { Route as localeChar123LocaleChar125BlogSlugRouteImport } from './routes/($locale)/{-$locale}/blog/$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const localeChar123LocaleChar125RouteRoute =
  localeChar123LocaleChar125RouteRouteImport.update({
    id: '/($locale)/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const localeChar123LocaleChar125IndexRoute =
  localeChar123LocaleChar125IndexRouteImport
    .update({
      id: '/',
      path: '/',
      getParentRoute: () => localeChar123LocaleChar125RouteRoute,
    } as any)
    .lazy(() =>
      import('./routes/($locale)/{-$locale}/index.lazy').then((d) => d.Route),
    )
const localeChar123LocaleChar125ContactRoute =
  localeChar123LocaleChar125ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => localeChar123LocaleChar125RouteRoute,
  } as any)
const localeChar123LocaleChar125BlogIndexRoute =
  localeChar123LocaleChar125BlogIndexRouteImport.update({
    id: '/blog/',
    path: '/blog/',
    getParentRoute: () => localeChar123LocaleChar125RouteRoute,
  } as any)
const localeChar123LocaleChar125BlogSlugRoute =
  localeChar123LocaleChar125BlogSlugRouteImport.update({
    id: '/blog/$slug',
    path: '/blog/$slug',
    getParentRoute: () => localeChar123LocaleChar125RouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}': typeof localeChar123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/contact': typeof localeChar123LocaleChar125ContactRoute
  '/{-$locale}/': typeof localeChar123LocaleChar125IndexRoute
  '/{-$locale}/blog/$slug': typeof localeChar123LocaleChar125BlogSlugRoute
  '/{-$locale}/blog/': typeof localeChar123LocaleChar125BlogIndexRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/contact': typeof localeChar123LocaleChar125ContactRoute
  '/{-$locale}': typeof localeChar123LocaleChar125IndexRoute
  '/{-$locale}/blog/$slug': typeof localeChar123LocaleChar125BlogSlugRoute
  '/{-$locale}/blog': typeof localeChar123LocaleChar125BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/($locale)/{-$locale}': typeof localeChar123LocaleChar125RouteRouteWithChildren
  '/($locale)/{-$locale}/contact': typeof localeChar123LocaleChar125ContactRoute
  '/($locale)/{-$locale}/': typeof localeChar123LocaleChar125IndexRoute
  '/($locale)/{-$locale}/blog/$slug': typeof localeChar123LocaleChar125BlogSlugRoute
  '/($locale)/{-$locale}/blog/': typeof localeChar123LocaleChar125BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sitemap.xml'
    | '/{-$locale}'
    | '/{-$locale}/contact'
    | '/{-$locale}/'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/{-$locale}/contact'
    | '/{-$locale}'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/blog'
  id:
    | '__root__'
    | '/sitemap.xml'
    | '/($locale)/{-$locale}'
    | '/($locale)/{-$locale}/contact'
    | '/($locale)/{-$locale}/'
    | '/($locale)/{-$locale}/blog/$slug'
    | '/($locale)/{-$locale}/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  localeChar123LocaleChar125RouteRoute: typeof localeChar123LocaleChar125RouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/($locale)/{-$locale}': {
      id: '/($locale)/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof localeChar123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/($locale)/{-$locale}/': {
      id: '/($locale)/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof localeChar123LocaleChar125IndexRouteImport
      parentRoute: typeof localeChar123LocaleChar125RouteRoute
    }
    '/($locale)/{-$locale}/contact': {
      id: '/($locale)/{-$locale}/contact'
      path: '/contact'
      fullPath: '/{-$locale}/contact'
      preLoaderRoute: typeof localeChar123LocaleChar125ContactRouteImport
      parentRoute: typeof localeChar123LocaleChar125RouteRoute
    }
    '/($locale)/{-$locale}/blog/': {
      id: '/($locale)/{-$locale}/blog/'
      path: '/blog'
      fullPath: '/{-$locale}/blog/'
      preLoaderRoute: typeof localeChar123LocaleChar125BlogIndexRouteImport
      parentRoute: typeof localeChar123LocaleChar125RouteRoute
    }
    '/($locale)/{-$locale}/blog/$slug': {
      id: '/($locale)/{-$locale}/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/{-$locale}/blog/$slug'
      preLoaderRoute: typeof localeChar123LocaleChar125BlogSlugRouteImport
      parentRoute: typeof localeChar123LocaleChar125RouteRoute
    }
  }
}

interface localeChar123LocaleChar125RouteRouteChildren {
  localeChar123LocaleChar125ContactRoute: typeof localeChar123LocaleChar125ContactRoute
  localeChar123LocaleChar125IndexRoute: typeof localeChar123LocaleChar125IndexRoute
  localeChar123LocaleChar125BlogSlugRoute: typeof localeChar123LocaleChar125BlogSlugRoute
  localeChar123LocaleChar125BlogIndexRoute: typeof localeChar123LocaleChar125BlogIndexRoute
}

const localeChar123LocaleChar125RouteRouteChildren: localeChar123LocaleChar125RouteRouteChildren =
  {
    localeChar123LocaleChar125ContactRoute:
      localeChar123LocaleChar125ContactRoute,
    localeChar123LocaleChar125IndexRoute: localeChar123LocaleChar125IndexRoute,
    localeChar123LocaleChar125BlogSlugRoute:
      localeChar123LocaleChar125BlogSlugRoute,
    localeChar123LocaleChar125BlogIndexRoute:
      localeChar123LocaleChar125BlogIndexRoute,
  }

const localeChar123LocaleChar125RouteRouteWithChildren =
  localeChar123LocaleChar125RouteRoute._addFileChildren(
    localeChar123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  localeChar123LocaleChar125RouteRoute:
    localeChar123LocaleChar125RouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
